#!/usr/bin/env python

import re
from twisted.application import internet, service
from twisted.internet import reactor
from twisted.words.protocols.jabber import client, jid, xmlstream
from twisted.words.xish import domish

class Qubot:
  def initFailed(self, failure):
    self.xmlstream.sendFooter()

  def message(self, recv):
    if recv['from'].startswith(unicode(jid)) and recv.body:
      send = recv

      del send['from']

      send['to'] = 'qubit@conference.jabber.org'
      send['type'] = 'groupchat'

      self.xmlstream.send(send)

    if 'qubit@conference.jabber.org/qubot' != recv['from'] and recv.body and re.search('qubot', str(recv.body), re.I):
      send = domish.Element((None, 'message'))

      send['to'] = 'qubit@conference.jabber.org'
      send['type'] = 'groupchat'

      send.addElement('body', content='don\'t taunt qubot')

      self.xmlstream.send(send)

  def authd(self, xmlstream):
    self.xmlstream = xmlstream

    # Send initial presence,
    # http://xmpp.org/internet-drafts/draft-saintandre-rfc3921bis-07.html#presence-initial
    presence = domish.Element((None, 'presence'))
    self.xmlstream.send(presence)

    self.xmlstream.addObserver('/message', self.message)

    presence = domish.Element((None, 'presence'))
    presence['to'] = 'qubit@conference.jabber.org/qubot'
    self.xmlstream.send(presence)

  def connected(self, xmlstream):
    self.xmlstream = xmlstream

    def rawDataIn(buf):
      print 'RECV: ' + buf

    def rawDataOut(buf):
      print 'SEND: ' + buf

    self.xmlstream.rawDataInFn = rawDataIn
    self.xmlstream.rawDataOutFn = rawDataOut

  def end(self, xmlstream):
    self.xmlstream = xmlstream

    reactor.stop()

qubot = Qubot()

jid = jid.JID('administrator@example.com')
password = 'example'

factory = client.XMPPClientFactory(jid, password)
factory.addBootstrap(xmlstream.INIT_FAILED_EVENT, qubot.initFailed)
factory.addBootstrap(xmlstream.STREAM_AUTHD_EVENT, qubot.authd)
factory.addBootstrap(xmlstream.STREAM_CONNECTED_EVENT, qubot.connected)
factory.addBootstrap(xmlstream.STREAM_END_EVENT, qubot.end)

application = service.Application('qubot')
service = internet.TCPClient('talk.google.com', 5222, factory)
service.setServiceParent(application)
